config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'


	devise_for :users,
	         path: '',
	         path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
	         controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show] #editがいらないのは、deviseで編集できるから。

  resources :rooms, except: [:edit] do
    member do
      get 'basic'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'youtube'
      get 'personalinfo'
      get 'teacher'
      get 'teacherinfo'
    end
    resources :reservations, only: [:create]
  end

  # 先生と生徒だけが見れるように。
  resources :reservations, only: [:show]

  get '/advices' => 'reservations#advices'
  get '/reservations' => 'reservations#reservations'  

  resources :teacher_reviews, only: [:create, :destroy]
  resources :student_reviews, only: [:create, :destroy]
  


  resources :roomphotos, only: [:create, :destroy] do
    collection do
      get :list 
    end
  end

  get '/search' => 'pages#search'


end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      M.toast({html: '<%= value %>'})
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer white">
  <hr color="#eeeeee">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="grey-text text-darken-2">SonoLigo</h5>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="grey-text text-darken-2">Links</h5>
        <ul>
          <li><a class="grey-text text-darken-2" href="#!">採用情報</a></li>
          <li><a class="grey-text text-darken-2" href="#!">SonoLigoとは</a></li>
          <li><a class="grey-text text-darken-2" href="#!">先生になるには</a></li>
          <li><a class="grey-text text-darken-2" href="#!">今後の展望</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-darken-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      M.toast({html: '<%= value %>'})
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='grey white'>
  <div class="container">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo grey-text text-darken-4">SonoLigo</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if (!user_signed_in?) %>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to '登録', new_user_registration_path %></li>
        <% else %>
          <li><%= link_to '楽器を登録する', new_room_path %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">
            <div class='chip white'>
              <%= image_tag avatar_url(current_user) %>
              <%= current_user.fullname %>
            </div>
            <i class="material-icons right">arrow_drop_down</i>
          </a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- PC時のdropdown  -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'プロフィールを編集', edit_user_registration_path %></li>
  <li><%= link_to "自分のリスティングを確認", rooms_path %></li>
  <li><%= link_to "自分の申し込みを確認", advices_path %></li>
  <% if @teacher_check %>
    <li><%= link_to "予約を確認", reservations_path %></li>
  <% end %>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
</ul>

<!-- スマホじのサイドバー -->
<ul class="sidenav" id="mobile-demo">
  <% if (!user_signed_in?) %>
    <li><%= link_to 'ログイン', new_user_session_path %></li>
    <li><%= link_to '登録', new_user_registration_path %></li>
  <% else %>
    <li><%= link_to 'プロフィールを編集', edit_user_registration_path %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>  <% end %>
</ul>

<script>
  $(".dropdown-trigger").dropdown();

  $(document).ready(function(){
    $('.sidenav').sidenav();
  });


  var elem = document.querySelector('.sidenav');
  var instance = M.Sidenav.init(elem, options);

  // Or with jQuery


</script>