config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'


	devise_for :users,
	         path: '',
	         path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
	         controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show] #editがいらないのは、deviseで編集できるから。

  resources :rooms, except: [:edit] do
    member do
      get 'basic'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'youtube'
      get 'personalinfo'
      get 'teacher'
      get 'teacherinfo'
    end
    resources :reservations, only: [:create]
  end

  # 先生と生徒だけが見れるように。
  resources :reservations, only: [:show]

  get '/advices' => 'reservations#advices'
  get '/reservations' => 'reservations#reservations'  

  resources :teacher_reviews, only: [:create, :destroy]
  resources :student_reviews, only: [:create, :destroy]
  


  resources :roomphotos, only: [:create, :destroy] do
    collection do
      get :list 
    end
  end

  get '/search' => 'pages#search'


end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  mount_uploader :audio, AudioUploader
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    room = Room.find(params[:room_id])

    if current_user == room.user
      flash[:notice] = "自分自身に対して申し込むことはできません。"
    # elsif current_user.stripe_id.blank?
    #   flash[:alert] = "Please update your payment method."
    #   return redirect_to payment_method_path
    else
    
      @reservation = current_user.reservations.build(reservation_params)
      @reservation.room = room
      @reservation.price = room.price

      @reservation.save

      flash[:notice] = "予約が完了しました。"
    end
    redirect_to room
  end

  def show
    @reservation = Reservation.find(params[:id])

    unless current_user == @reservation.user || current_user == @reservation.room.user
      flash[:notice] = "アクセスする権限がありません。"
      redirect_to root_path
    end

    @teacher = @reservation.room.user
    @student = @reservation.user


  end

  def advices
    @rooms = current_user.rooms
    @advices = current_user.reservations
  end

  def reservations
    @rooms = current_user.rooms
  end


  private
  def reservation_params
      params.require(:reservation).permit(:title, :content, :audio, :audio_cache)
  end
end

app/views/reservations/_form.html.erb
<div class="card">
  <div class="card-content">
    <p class="red-text text-darken-4"><i class="material-icons tiny  red-text text-darken-4">star</i><%= @user.fullname %>さんは先生として認証済みです。</p>
  </div>
  <div class="card-tabs">
    <ul class="tabs tabs-fixed-width">
      <% if @room.begginer %>
        <li class="tab"><a href="#level1">初心者</a></li>
      <% end %>
      <% if @room.middle %>
        <li class="tab"><a href="#level2">中級者</a></li>
      <% end %>
      <% if @room.expert %>
        <li class="tab"><a href="#level3">上級者</a></li>
      <% end %>
    </ul>
  </div>
  <div class="card-content grey lighten-4">
    <% if @room.begginer %>
      <div id="level1">初心者を指導可能です。</div>
    <% end %>
    <% if @room.middle %>
      <div id="level2">中級者を指導可能です。</div>
    <% end %>
    <% if @room.expert %>
      <div id="level3">上級者を指導可能です。</div>
    <% end %>
  </div>
  <div class="card-content">
    <p>曲を送って、詳細なアドバイスをもらいましょう。</p>
    <p><em><%= @room.price %>円/一曲あたりのアドバイス料</em></p>
    <br>

    <div class="row">
      <div class="button-center">
        <button class="btn waves-effect waves-light grey darken-1 modal-trigger" href="#modal1" >アドバイスを申し込む。
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <%= form_for([@room, @room.reservations.new]) do |f| %>
    <div class="modal-content">
      <h4>予約前の確認</h4>
      <p>先生に申し込む初めての場合は、事前に先生にメッセージをして曲目を確認しましょう。</p>
      <br>
      <div class="input-field">
        <%= f.text_field :title, autofocus: true,required: true ,id: "title"%>
        <label for="title">曲名</label>
      </div>
      <div class="input-field">
        <%= f.text_area :content,required: true ,id: "content", class: "materialize-textarea"%>
        <label for="content">内容の詳細</label>
      </div>

      <div class="file-field input-field">
        <div class="btn grey darken-1 ">
          <span>音声ファイルを選択</span>
          <%= f.file_field  :audio, required: true  %>
          <%= f.hidden_field :audio_cache %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>


    </div>
    <div class="modal-footer">
      <div class="button-center">
        <button class="btn waves-effect waves-light red darken-4" type="submit" name="action" >アドバイスを申し込む。
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
  <% end %>
</div>

<script>

  $(document).ready(function(){
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('.modal').modal();
  });

</script>

app/views/reservations/advices.html.erb
<% @teacher_check = false %>

<% @rooms.each do |room| %>
  <% if room.teacher_auth %>
    <% @teacher_check = true %>
  <% end %>
<% end %>

<div class="row">
  <div class="col m3 s12">
    <ul class="collection">
      <li class= "collection-item <%= 'grey darken-1' if action_name == "advices" %>">
        <div>
          <%= link_to "アドバイス一覧", advices_path, class: " #{'white-text' if action_name == "advices" } #{'grey-text text-darken-1' if action_name != "advices" } " %>
        <div>
      </li>
      <% if @teacher_check %>
        <li class= "collection-item <%= 'grey darken-1' if action_name == "reservations" %>">
          <div>
            <%= link_to "予約一覧", reservations_path, class: " #{'white-text' if action_name == "reservations" } #{'grey-text text-darken-1' if action_name != "reservations" } " %>
          <div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col m9 s12">
    <div class="row">
      <% @advices.each do |advice| %>
        <div class="col m6 s12">
          <div class="card ">
            <div class="card-image">
              <%= link_to room_path(advice.room) do %>
                <%= image_tag advice.room.cover_photo(:medium) %>
              <% end %>
            </div>
            <div class="card-content">
              <span class="center-align">
                <%= link_to user_path(advice.user) do %>
                  <div class="chip white">
                    <%= image_tag avatar_url(advice.user), class: "img-circle avatar-small" %>
                    <%= advice.user.fullname %>
                  </div>
                <% end %>先生へのアドバイス申し込み
              </span>
              <p class="right-align"><%= advice.created_at.strftime('%Y年%m月%d日') %></p>
            </div>
            <div class="card-action">
              <div class="button-center">
                <%= link_to  reservation_path(advice), class: 'btn waves-effect waves-light grey darken-1' do %>
                  <span>詳細を見る</span><i class="material-icons right">send</i>
                <% end %>
              </div>
              room.id 
              <%= advice.room.id %>
              reservatino.id 
              <%= advice.id %>
              <div class="text-right">
                <%= render partial: "reviews/student_form", locals: {reservation: advice} %>
              </div>
            </div>    
          </div>   
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/reservations.html.erb
<% @teacher_check = false %>

<% @rooms.each do |room| %>
  <% if room.teacher_auth %>
    <% @teacher_check = true %>
  <% end %>
<% end %>


<div class="row">
  <div class="col m3 s12">
    <ul class="collection">
      <li class= "collection-item <%= 'grey darken-1' if action_name == "advices" %>">
        <div>
          <%= link_to "アドバイス一覧", advices_path, class: " #{'white-text' if action_name == "advices" } #{'grey-text text-darken-1' if action_name != "advices" } " %>
        </div>
      </li>
      <% if @teacher_check  %>
        <li class= "collection-item <%= 'grey darken-1' if action_name == "reservations" %>">
          <div>
            <%= link_to "予約一覧", reservations_path, class: " #{'white-text' if action_name == "reservations" } #{'grey-text text-darken-1' if action_name != "reservations" } " %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col m9 s12">
    <div class="row">
      <% @rooms.each do |room| %>
        <% room.reservations.each do |reservation| %>
          <div class="col m6 s12">
            <div class="card ">
              <div class="card-image">
                <%= link_to room_path(reservation.room) do %>
                  <%= image_tag reservation.room.cover_photo(:medium) %>
                <% end %>
              </div>
              <div class="card-content">
                <span class="center-align">
                  <%= link_to user_path(reservation.user) do %>
                    <div class="chip white">
                      <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                      <%= reservation.user.fullname %>
                    </div>
                  <% end %>さんからの申し込み
                </span>
                <p class="right-align"><%= reservation.created_at.strftime('%Y年%m月%d日') %></p>
              </div>
              <div class="card-action">
                <div class="button-center">
                  <%= link_to  reservation_path(reservation), class: 'btn waves-effect waves-light grey darken-1' do %>
                    <span>詳細を見る</span><i class="material-icons right">send</i>
                  <% end %>
                </div>
                reservation id
                <%= reservation.id %>
                reservation.room.id
                <%= reservation.room.id %>
                <div class="text-right">
                  <%= render partial: "reviews/teacher_form", locals: {reservation: reservation}   %>
                </div>
              </div>    
            </div>   
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>