config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'


	devise_for :users,
	         path: '',
	         path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
	         controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show] #editがいらないのは、deviseで編集できるから。

  resources :rooms, except: [:edit] do
    member do
      get 'basic'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'youtube'
      get 'personalinfo'
      get 'teacher'
      get 'teacherinfo'
    end
    resources :reservations, only: [:create]
  end

  # 先生と生徒だけが見れるように。
  resources :reservations, only: [:show]

  get '/advices' => 'reservations#advices'
  get '/reservations' => 'reservations#reservations'  

  resources :teacher_reviews, only: [:create, :destroy]
  resources :student_reviews, only: [:create, :destroy]
  


  resources :roomphotos, only: [:create, :destroy] do
    collection do
      get :list 
    end
  end

  get '/search' => 'pages#search'


end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :roomphotos
  has_many :reservations

  has_many :student_reviews

  validates :instrument, presence: true

  def cover_photo(size)
    if self.roomphotos.length > 0
      self.roomphotos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    student_reviews.count == 0 ? 0 : student_reviews.average(:star).round(2).to_i
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_action :set_room ,except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:basic, :pricing, :description, :photo_upload, :youtube, :teacher, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to basic_room_path(@room), notice: '保存されました！'
    else
      render :new, notice: '間違いがあります。もう一度やり直してください。'
    end
  end

  def show
    @user = @room.user
    @photos = @room.roomphotos

    @student_reviews = @room.student_reviews
  end

  def basic
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photo = Roomphoto.new
  end

  def youtube
  end

  def teacher
  end

  def personalinfo
    @user = current_user
  end

  def teacherinfo
    @user = current_user
  end

  def update

    # new_params = room_params
    # new_params = room_params.merge(active: true) if is_ready_room

    if @room.update(room_params)
      flash[:notice]='Saved...'
    else
      flash[:notice]='Something went wrong...'
    end

    redirect_back(fallback_location: request.referer)

  end

  private 
    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def room_params
      params.require(:room).permit(:instrument, :summary, :teach_years , :exp_years, :price, :youtube1, :youtube2, :youtube3, :begginer, :middle, :expert, :teacher_apply, :teacher_auth, :active)
    end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_room_menu.html.erb
<% @basic = !@room.instrument.blank? && !@room.exp_years.blank? %>

<% @personal_info= !current_user.fullname.blank? && !current_user.description.blank? %>

<% @room_params =  !@room.begginer.blank? || !@room.middle.blank? || !@room.expert.blank? %>

<% @teach_params = @room_params && !@room.price.blank? && !@room.teach_years.blank? && !@room.youtube1.blank? && !@room.roomphotos.blank? %>

<% @teach_info = !current_user.fullname.blank? && !current_user.description.blank? && !current_user.belong.blank? && !current_user.award.blank?  %>

<div class="col m3 s12">
  <ul class="collection">
    <li class= "collection-item <%= 'grey darken-1' if action_name == "basic" %>">
      <div>
        <%= link_to "基本情報", basic_room_path, class: " #{'white-text' if action_name == "basic" } #{'grey-text text-darken-1' if action_name != "basic" } " %>
        <a class="secondary-content">
          <% if @basic == true %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
        </a>
      </div>
    </li>

    <% if !@room.teacher_apply %>
      <li class= "collection-item <%= 'grey darken-1' if action_name == "personalinfo" %>">
        <div>
          <%= link_to "個人情報", personalinfo_room_path, class: " #{'white-text' if action_name == "personalinfo" } #{'grey-text text-darken-1' if action_name != "personalinfo" } " %>
          <a class="secondary-content">
            <% if @personal_info %>
              <i class="material-icons cyan-text">check</i>
            <% else %>
              <i class="material-icons deep-orange-text">clear</i>
            <% end %>
          </a>
        </div>
      </li>
    <% end %>

    <li class= "collection-item <%= 'grey darken-1' if action_name == "photo_upload" %>">
      <div>
        <%= link_to "写真", photo_upload_room_path, class: " #{'white-text' if action_name == "photo_upload" } #{'grey-text text-darken-1' if action_name != "photo_upload" } " , data: { turbolinks: false } %>
        <a class="secondary-content">
          <% if !@room.roomphotos.blank? && @room.teacher_apply %>
            <i class="material-icons cyan-text">check</i>
          <% elsif @room.roomphotos.blank? && @room.teacher_apply %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
        </a>
      </div>
    </li>

    <li class= "collection-item <%= 'grey darken-1' if action_name == "youtube" %>">
      <div>
        <%= link_to "YouTube", youtube_room_path, class: " #{'white-text' if action_name == "youtube" } #{'grey-text text-darken-1' if action_name != "youtube" } " %>
        <a class="secondary-content">
          <% if !@room.youtube1.blank? && @room.teacher_apply %>
            <i class="material-icons cyan-text">check</i>
          <% elsif @room.youtube1.blank? && @room.teacher_apply %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
        </a>
      </div>
    </li>

    <li class= "collection-item <%= 'grey darken-1' if action_name == "teacher" %>">
      <div>
        <%= link_to "先生になるには", teacher_room_path, class: " #{'white-text' if action_name == "teacher" } #{'grey-text text-darken-1' if action_name != "teacher" } " %>
        <a class="secondary-content">
          <% if @teach_params && @room.teacher_apply %>
            <i class="material-icons cyan-text">check</i>
          <% elsif  !@teach_params && @room.teacher_apply %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
        </a>
      </div>
    </li>



    <% if @room.teacher_apply == true  %>
      <li class= "collection-item <%= 'grey darken-1' if action_name == "teacherinfo" %>">
        <div>
          <%= link_to "個人情報", teacherinfo_room_path, class: " #{'white-text' if action_name == "teacherinfo" } #{'grey-text text-darken-1' if action_name != "teacherinfo" } " %>
          <a class="secondary-content">
            <% if @teach_info == true %>
              <i class="material-icons cyan-text">check</i>
            <% else %>
              <i class="material-icons deep-orange-text">clear</i>
            <% end %>
          </a>
        </div>
      </li>
    <% end %>
  </ul>   


  <div class="row button-center">

    <!-- 生徒用 -->
    <% if !@room.teacher_apply  && !@room.active && @basic && @personal_info %>
      <%= form_for @room do |f| %>
        <%= f.hidden_field :active, value: true %>
        <button class="btn waves-effect waves-light cyan" type="submit" name="action" >公開する
          <i class="material-icons right">public</i>
        </button>      
      <% end %>
    <% end %>

    <% if @room.active %>
      <%= form_for @room do |f| %>
        <%= f.hidden_field :active, value: false %>
        <button class="btn waves-effect waves-light deep-orange" type="submit" name="action" >公開をやめる
          <i class="material-icons right">public</i>
        </button>
      <% end %>
    <% end %>

    <!-- teacher_applyの申請が通る前。 -->
    <% if @room.teacher_apply && !@room.teacher_auth && @teach_params && @teach_info %>
      <%= link_to "先生として公開する審査へ。", root_path,  class: "btn waves-effect waves-light cyan" %>
    <% end %>


    <!-- teacher_applyの申請が通った後。 -->
    <% if @room.teacher_apply && @room.teacher_auth && !@room.active  %>
      <%= form_for @room do |f| %>
        <%= f.hidden_field :active, value: true %>
        <button class="btn waves-effect waves-light cyan" type="submit" name="action" >先生として公開する
              <i class="material-icons right">public</i>
        </button>
      <% end %>
    <% end %>

    <% if @room.teacher_apply && !@room.teacher_auth %>
      本来ここは、サイト上では見せないが、いまは簡略化のため。
      <%= form_for @room do |f| %>
        <%= f.hidden_field :teacher_auth, value: true %>
        <button class="btn waves-effect waves-light cyan" type="submit" name="action" >先生として許可する。
              <i class="material-icons right">star</i>
        </button>
      <% end %>
    <% end %>

    <% if @room.teacher_apply && @room.teacher_auth %>
      本来ここは、サイト上では見せないが、いまは簡略化のため。
      <%= form_for @room do |f| %>
        <%= f.hidden_field :teacher_auth, value: false %>
        <button class="btn waves-effect waves-light cyan" type="submit" name="action" >先生として不許可にする。
              <i class="material-icons right">star</i>
        </button>
      <% end %>
    <% end %>
  </div>

</div>

app/views/rooms/basic.html.erb
<div class="row">
  <%= render "rooms/room_menu" %>

  <div class="col m9 s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title center-allign">基本情報</span>

        <%= form_for @room do |f| %>

          <div class="row">
            <div class="col m6">
              <div class="input-field">
                <%= f.text_field :instrument , disabled: 'disabled'%>
                <label class="active" >楽器</label>
              </div>
            </div>
            <div class="col m6">
              <div class="input-field">
                <%= f.select :exp_years, [["1年", 1], ["2年", 2],["3年", 3], ["4年", 4],["5年", 5], ["6年", 6],["7年", 7], ["8年", 8],["9年", 9], ["10年", 10],["10年以上", 11]], prompt: "選択する。" %>
                <label>経験歴</label>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="button-center">
              <button class="btn waves-effect waves-light grey darken-1" type="submit" name="action" >更新する
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function(){
    $('select').formSelect();
  });
</script>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<h1>Room#description</h1>
<p>Find me in app/views/room/description.html.erb</p>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col m3">
    <ul class="collection">
      <li class= "collection-item <%= 'grey darken-1' if action_name == "index" %>">
        
          <%= link_to "あなたの楽器一覧", rooms_path, class: " #{'white-text' if action_name == "index" } #{'grey-text text-darken-1' if action_name != "index" } " %>
      </li>
    </ul>    
　</div>

  <div class="col m9">
    <ul class="collection">
      <% @rooms.each do |room|  %>
        <li class="collection-item avatar">
          <% unless room.roomphotos.blank? %>
            <%= image_tag room.cover_photo(:medium),class: "circle" %>
          <% else %>
            <i class="material-icons circle">play_arrow</i></a>
          <% end %>
          <span class="title"><%= room.instrument %></span>
          <p>
            <%= link_to "内容を更新する", basic_room_path(room) %>
          </p>
          <% if room.teacher_auth == true %>
            <a href="#!" class="secondary-content"><i class="material-icons medium deep-orange-text text-darken-4">stars</i></a>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">楽器を選択しよう！</span>
        
        <%= form_for @room do |f| %>

          <div class="row">
            <div class="col s12 m4">
              <p>木管楽器</p>  
              <p>
                <label>
                  <%= f.radio_button :instrument, 'サックス'  %>
                  <span>サックス</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'クラリネット'  %>
                  <span>クラリネット</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'フルート'  %>
                  <span>フルート</span>
                </label>
              </p>
            </div>

            <div class="col s12 m4">
              <p>金管楽器</p>  
              <p>
                <label>
                  <%= f.radio_button :instrument, 'トランペット'  %>
                  <span>トランペット</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'トロンボーン'  %>
                  <span>トロンボーン</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'ホルン'  %>
                  <span>ホルン</span>
                </label>
              </p>
            </div>

            <div class="col s12 m4">
              <p>金管楽器</p>  
              <p>
                <label>
                  <%= f.radio_button :instrument, 'トランペット'  %>
                  <span>トランペット</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'トロンボーン'  %>
                  <span>トロンボーン</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'ホルン'  %>
                  <span>ホルン</span>
                </label>
              </p>
            </div>

            <div class="col s12 m4">
              <p>金管楽器</p>  
              <p>
                <label>
                  <%= f.radio_button :instrument, 'トランペット'  %>
                  <span>トランペット</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'トロンボーン'  %>
                  <span>トロンボーン</span>
                </label>
              </p>

              <p>
                <label>
                  <%= f.radio_button :instrument, 'ホルン'  %>
                  <span>ホルン</span>
                </label>
              </p>
            </div>
          </div>

          <div class="button-center">
            <button class="btn waves-effect waves-light grey darken-1" type="submit" >選択
              <i class="material-icons right">send</i>
            </button>
          </div>



        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/personalinfo.html.erb
<div class="row">
  <%= render "rooms/room_menu" %>

  <div class="col m9 s12">

    <p>公開するために、以下のユーザー情報を全て登録する必要があります。</p>

    <ul class="collapsible">
      <li>
        <div class="collapsible-header">
          <% unless @user.fullname.blank? %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
          名前
        </div>
        <div class="collapsible-body"><span><%= @user.fullname %></span></div>
      </li>

      <li>
        <div class="collapsible-header">
          <% unless @user.description.blank? %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
          自己紹介
        </div>
        <div class="collapsible-body"><span><%= @user.description %></span></div>
      </li>
    </ul>

    <div class="row">
      <div class="button-center">
        <%= link_to  edit_user_registration_path, class: 'btn waves-effect waves-light grey darken-1' do %>
          <span>プロフィールを編集する</span><i class="material-icons right">send</i>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <%= render "rooms/room_menu" %>

  <div class="col m9 s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title center-allign">写真アップロード</span>

        <%= form_for @photo, html: {multipart: true, class:"dropzone", id:"my-dropzone"} do |f| %>

          <%= f.hidden_field :room_id, value: @room.id %>
          <div class="dz-message needsclick">
              <h5>ファイルをここにドロップしてください。</h5>
              <strong>アップロードするにはここをクリックしてください</strong>
          </div>

          <div class="fallback">
              <%= f.file_field :image %>
              <%= f.submit "Upload image" %>
          </div>


        <% end %>

        <div id="photos"><%= render 'roomphotos/roomphotos_list' %></div>

      </div>
    </div>
  </div>
</div>


<!-- dropzone.js -->
<script type="text/javascript">
  $(function () {
  Dropzone.autoDiscover = false;
  //photos_controller.rbのcreateアクションが呼ばれる
  $("#my-dropzone").dropzone({
    maxFilesize: 50,// MB
    addRemoveLinks: true,//削除リンク,Cancelリンクを全てのpreviewファイルに付ける。 
    paramName: 'roomphoto[image]',// パラメータの名前
    success: function(file, response) {
      // file.previewElementでpreview要素のhtmlにアクセスできる
      //add .dz-success class to file.previewElement 
      $(file.previewElement).addClass('dz-success');
      //add response.uploadId to .dz-remove class
      $(file.previewElement).find('.dz-remove').attr('id', response.photoId);
    },
    removedfile: function(file) {
      // 削除選択されたfileのidを取得
      var id = $(file.previewTemplate).find('.dz-remove').attr('id');
      //call photos_controler.rb destroy action
      $.ajax({
        type: 'DELETE',
        url: "/roomphotos/" + id,
        success: function(data) {
          console.log(data.message);
        }
      });

      var previewElement;
      // 条件式 ? 式1 : 式2　条件式の値がtrue=>式1、false=>式2返します。
      //parentNode => 親ノード（一つ上のhtml要素)を取得.
      //(void 0) => 何も処理しない
      // リスト（親ノード）から、プレビュー要素を消すという記述
      return (previewElement = file.previewElement) != null ? (previewElement.parentNode.removeChild(file.previewElement)) : (void 0);
    },
    // init executed at first when Page loaded
    init: function() {
      //this equal dropzone
      var me = this;

      //meに"complete"イベントを定義
      me.on("complete", function(file) {
       $(file.previewTemplate).find('.dz-remove').text("削除する");
      }); 
      //call list function in photos_controller.rb with get method
      $.ajax({
       type: "GET",
       url: "/roomphotos/list",
       data: {'room_id': <%= @room.id %>},
           dataType: 'json',
       success: function(data){
           $.each(data.images, function(key, value) {
             if (data.images != undefined && data.images.length > 0) {
               me.emit("addedfile", value); //addedfileイベントをvalueのデータで実行する
               me.emit("thumbnail", value, value.src);//thumbnailイベントをvalueのデータで実行する
               me.emit("complete", value);  //completeイベントをvalueのデータで実行する
               $(value._removeLink).attr("id", value.id); //valueの_removeLinkのidにvalue.idを追加
             }
           });
       }
      });
    }
  });
});
</script>

app/views/rooms/pricing.html.erb
<h1>Room#pricing</h1>
<p>Find me in app/views/room/pricing.html.erb</p>

app/views/rooms/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col s12">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <% @photos.each do |photo| %>
          <div class="swiper-slide">
            <img src='<%= photo.image.url(:slider) %>)'  class="responsive-img" />
          </div> 
        <% end %>
      </div>

      <div class="swiper-pagination"></div>      
      <div class="swiper-button-prev "></div>
      <div class="swiper-button-next"></div>
    </div>
  </div>  
</div>
<br/>



<div class="row">
  <div class="col m12 l8">
    <div class="col s12">
      <ul class="collection with-header z-depth-1">
        <li class="collection-header"><h5><%= @user.fullname %></h5><%= @room.instrument %></li>
        <li class="collection-item"><%= @user.description %></li>
        <li class="collection-item">所属</li>
        <li class="collection-item"><p><%= @user.belong %></p></li>
        <li class="collection-item">受賞歴</li>
        <li class="collection-item"><p><%= @user.award %></p></li>
      </ul>
    </div>

    <div class="col s12">
      <h3>
        <span id="average_rating"></span>
      </h3>
      <div class="col s12">
        <div><%= render "reviews/student_list" %></div>
      </div>
    </div>
  </div>

  <div class="col m12 l4 ">
    <% if @room.teacher_auth && @room.active && @room.teacher_apply && current_user != @room.user %>
      <%= render 'reservations/form' %>
    <% end %>
  </div>
</div>

<script>
    var swiper = new Swiper('.swiper-container', {
      slidesPerView: 1,
      spaceBetween: 30,
      centeredSlides: true,
      loop: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
</script>

<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });

  $(document).ready(function(){
    $('.tabs').tabs();
  });
</script>

app/views/rooms/teacher.html.erb
<div class="row">
  <%= render "rooms/room_menu" %>

  <div class="col m9 s12">

    <%= form_for @room do |f| %>
      <div class="card">
        <div class="card-content">
          <span class="card-title center-align teal-text text-darken-2">先生の情報</span>

          <div class="row button-center">
            <div class="switch">
              <p>先生になる。</p>
              <label>
                Off
                <%= f.check_box :teacher_apply %>
                <span class="lever"></span>
                On
              </label>
            </div>
          </div> 

          <div class="row">
            <div class="button-center">
              <button class="btn waves-effect waves-light grey darken-1" type="submit" name="action" >更新する
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        </div>
      </div>



      <% if @room.teacher_apply == true %>
      <div class="card">
        <div class="card-content">
          <span class="card-title center-align teal-text text-darken-2">先生の情報</span>
          <br>
            <div class="row">
              <p>先生として登録するためには、全ての情報を入力する必要があります。</p>
            </div>

            <div class="row">
              <div class="col s12 m6">
                <div class="input-field">
                  <%= f.text_field :price ,placeholder:':円'  %>
                  <label class="active">値段</label>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col s12 m4">
                <h5>指導年数</h5>
                <div class="input-field">
                  <%= f.select :teach_years, [["1年", 1], ["2年", 2],["3年", 3], ["4年", 4],["5年", 5], ["6年", 6],["7年", 7], ["8年", 8],["9年", 9], ["10年", 10],["10年以上", 11]], prompt: "選択する。" %>
                  <label>指導歴</label>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col s12 m6">
                <h5>指導可能レベル</h5>
                <p>少なくとも一つチェックしてください。</p>
                <p>
                  <label>
                    <%= f.check_box :begginer, class: "filled-in" %>
                    <span>初級者</span>
                  </label>
                </p>

                <p>
                  <label>
                    <%= f.check_box :middle, class: "filled-in" %>
                    <span>中級者</span>
                  </label>
                </p>

                <p>
                  <label>
                    <%= f.check_box :expert, class: "filled-in" %>
                    <span>上級者</span>
                  </label>
                </p>
              </div>  

              <div class="col s12">
                <h5>Youtube</h5>
                <div class="input-field">
                  <%= f.text_field :youtube1 %>
                  <label class="active">Youtube</label>
                </div>

                <% unless @room.youtube1.blank? %>
                  <% @youtube1_embed = @room.youtube1.gsub("watch?v=","embed/") %>
                  <div class="video-container" >
                    <iframe src="<%= @youtube1_embed %>" frameborder="0" allowfullscreen></iframe>
                  </div>
                <% end %>
              </div>
            </div>
          
            <div class="row">
              <div class="button-center">
                <button class="btn waves-effect waves-light grey darken-1" type="submit" name="action" >更新する
                  <i class="material-icons right">send</i>
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<script>
    $(document).ready(function(){
    $('select').formSelect();
  });
</script>

app/views/rooms/teacherinfo.html.erb
<div class="row">
  <%= render "rooms/room_menu" %>

  <div class="col m9 s12">

    <p>先生として登録するために、以下のユーザー情報を全て登録する必要があります。</p>

    <ul class="collapsible">
      <li>
        <div class="collapsible-header">
          <% unless @user.fullname.blank? %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
          名前
        </div>
        <div class="collapsible-body"><span><%= @user.fullname %></span></div>
      </li>

      <li>
        <div class="collapsible-header">
          <% unless @user.description.blank? %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
          自己紹介
        </div>
        <div class="collapsible-body"><span><%= @user.description %></span></div>
      </li>

      <li>
        <div class="collapsible-header">
          <% unless @user.belong.blank? %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
          所属歴
        </div>
        <div class="collapsible-body"><span><%= @user.belong %></span></div>
      </li>

      <li>
        <div class="collapsible-header">
          <% unless @user.award.blank? %>
            <i class="material-icons cyan-text">check</i>
          <% else %>
            <i class="material-icons deep-orange-text">clear</i>
          <% end %>
          受賞歴
        </div>
        <div class="collapsible-body"><span><%= @user.award %></span></div>
      </li>
    </ul>

    <div class="row">
      <div class="button-center">
        <%= link_to  edit_user_registration_path, class: 'btn waves-effect waves-light grey darken-1' do %>
          <span>プロフィールを編集する</span><i class="material-icons right">send</i>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>

app/views/rooms/youtube.html.erb
<div class="row">
  <%= render "rooms/room_menu" %>

  <div class="col m9 s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title center-allign">Youtube</span>

        <%= form_for @room do |f| %>

          <div class="row">
            <div class="col s12">
              <div class="input-field">
                <%= f.text_field :youtube1 %>
                <label class="active">Youtube</label>
              </div>
        
              <% unless @room.youtube1.blank? %>
                <% @youtube1_embed = @room.youtube1.gsub("watch?v=","embed/") %>
                <div class="video-container" >
                  <iframe src="<%= @youtube1_embed %>" frameborder="0" allowfullscreen></iframe>
                </div>
              <% end %>
            </div>

            <div class="col s12">
              <div class="input-field">
                <%= f.text_field :youtube2 %>
                <label class="active">Youtube</label>
              </div>

              <% unless @room.youtube2.blank? %>
                <% @youtube2_embed = @room.youtube2.gsub("watch?v=","embed/") %>
                <div class="video-container" >
                  <iframe src="<%= @youtube2_embed %>" frameborder="0" allowfullscreen></iframe>
                </div>
              <% end %>
            </div>

            <div class="col s12">
              <div class="input-field">
                <%= f.text_field :youtube3 %>
                <label class="active">Youtube</label>
              </div>

              <% unless @room.youtube3.blank? %>
                <% @youtube3_embed = @room.youtube3.gsub("watch?v=","embed/") %>
                <div class="video-container" >
                  <iframe src="<%= @youtube3_embed %>"  frameborder="0" allowfullscreen></iframe>
                </div>
              <% end %>
            </div>

          </div>

          <div class="row">
            <div class="button-center">
              <button class="btn waves-effect waves-light grey darken-1" type="submit" name="action" >更新する
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        
        <% end %>
      </div>
    </div>
  </div>
</div>